import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Title from "../components/Navbar";
import { isConstructorDeclaration } from "typescript";
import React, { createContext, forwardRef } from "react";

const inter = Inter({ subsets: ["latin"] });

const backgroundColor = createContext("#313131");

export default function Home() {
  React.forwardRef(
    (
      props: React.PropsWithChildren,
      ref: React.RefObject<HTMLHeadingElement>
    ) => {
      <div>
        <Head>
          <title>Purdue GarageHack 2023</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1 className={styles.coding} ref={ref}>
            Coding, but in a parking garage
          </h1>
          <p>That could be cool, bring your friends!</p>
          {props.children}
        </main>
      </div>;
    }
  );
}
