import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Title from "../components/Navbar";
import React, { useState, createContext } from "react";
import { isConstructorDeclaration } from "typescript";

const inter = Inter({ subsets: ["latin"] });

const backgroundColor = createContext("#313131");

export default function Home() {
  var myRef = React.createRef();
  const [MousePosition, setMousePosition] = useState({
    left: 0,
  });

  function handleMouseMove(ev) {
    setMousePosition({ left: ev.pageX });
    console.log(MousePosition.left);
  }
  return (
    <div onMouseMove={(ev) => handleMouseMove(ev)}>
      <Head>
        <title>Purdue GarageHack 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.coding}>Coding, but in a parking garage</h1>
        <p>That could be cool, bring your friends!</p>
      </main>
    </div>
  );
}
