import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { createContext } from 'react'
import Title from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

const backgroundColor = createContext("#313131")

export default function Home() {
  return (
    <>
      <Head>
        <title>Purdue GarageHack 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {" "}
        <Title />

        
      </main>
    </>
  )
}
